#!/bin/bash -x

cd `dirname $0`

mkdir -p .sync

if [ -f containerSync ] ; then
exit

fi

touch containerSync

#interval=0.02
interval=0.1

if [ "X$1" != "X" ] ; then
interval=$1
fi

PATH=$PATH:/usr/local/bin

cd `dirname $0`
source .env
#container=`docker ps | grep kness | sed 's/.*my/my/'`
container=${PROJECT_NAME}_php
#echo $container

files=`docker exec -i $container bash -c "find /var/www/html -type f -mmin -$interval | grep -v cache"`

#echo $files

for x in $files 
do


excludeFile=`echo $x | grep $syncExclude `
if [  "X$excludeFile" = "X" ] ; then
#echo $x
local_file=`echo $x | sed 's@/var/www/html/@@' | sed "s@$syncDir@.save.${syncDir}@" | sed 's@^/@@'` 
echo "$x -> $local_file"
dir=`dirname $local_file`
#echo $dir
mkdir -p .sync/$dir
docker cp ${container}:$x .sync/$local_file

else 
echo $x not copied
fi

done

for x in $files
do


excludeFile=`echo $x | grep $syncExclude `
if [  "X$excludeFile" = "X" ] ; then

local_file=`echo $x | sed 's@/var/www/html/@@' | sed "s@$syncDir@.save.${syncDir}@"`
real_local_file=`echo $x | sed 's@/var/www/html/@@' | sed "s@^@$WEB_ROOT/@"`
real_local_file_dir=`dirname $real_local_file`
echo rrrrrr "XX $real_local_file_dir XX"
if [ ! -d $real_local_file_dir ] ; then
   mkdir -p $real_local_file_dir
fi

echo "$local_file -> $real_local_file"
#docker cp ${container}:$x .sync/$local_file
echo cp .sync/$local_file  $real_local_file
diff=`diff .sync/$local_file  $real_local_file 2>/dev/null`
echo "1 $diff"
if [ "X$diff" != "X" -o ! -f $real_local_file ] ; then
echo "2 $diff"
cp .sync/$local_file  $real_local_file

else
sleep 0.1
fi

fi

done

#rm -rf .sync

rm containerSync
